/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://3rpqfo7rvng5pnfph7e4sspaf4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_cognito_identity_pool_id": "us-east-2:c7145c97-7f91-409c-87a6-4d7a51c93616",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_dSKJrK9d5",
    "aws_user_pools_web_client_id": "6028u6s9j1q52l45gqk5ppp1ht",
    "oauth": {},
    "aws_user_files_s3_bucket": "alldays41f4d952d88e47f28c621705881a2ff705822-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
